---
# tasks file for vlc

- name: Install VLC
  sudo: true
  dnf: name=vlc state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: vlc
