---
# tasks file for fish

- name: Install fish
  sudo: true
  dnf: name=fish state=present
  when: ansible_pkg_mgr == "dnf"
  tags: fish

- name: Install fish
  sudo: true
  yum: name=fish state=present
  when: ansible_pkg_mgr == "yum"
  tags: fish

- name: Set user's shell to fish
  sudo: true
  user: name={{ item.name }} shell=/usr/bin/fish
  when: item.shell == "fish"
  with_items: users
  tags: fish
