---
# tasks file for fish

- name: install fish
  sudo: true
  yum: pkg=fish state=present
  tags: fish

- name: create configuration directory for current user
  file: >
    path={{ fish_config_dir }}
    state=directory
    owner={{ username }}
    group={{ username }}
    mode=0755
  tags: fish

- name: copy fish config file for current user
  copy: >
    src=config.fish
    dest={{ fish_config_dir }}
    owner={{ username }}
    group={{ username }}
    mode=0644
  tags: fish

- name: copy fish functions for current user
  copy: >
    src=functions/
    dest={{ fish_config_dir }}/functions
    owner={{ username }}
    group={{ username }}
    directory_mode=0755
    mode=0644
  tags: fish

- name: set shell to fish for current user
  sudo: true
  user: name={{ username }} shell=/usr/bin/fish
  tags: fish

