---
# tasks file for fish

- name: Add fish repository
  sudo: true
  get_url: >
    url={{ fish_centos_repo }}
    dest=/etc/yum.repos.d/fish.repo
    owner=root
    group=root
    mode=0644
  when: ansible_distribution == "CentOS"
  tags: fish

- name: Install fish
  sudo: true
  dnf: name=fish state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: fish

- name: Install fish
  sudo: true
  yum: name=fish state=present
  when: ansible_pkg_mgr == "yum" and not (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: fish

- name: Set user's shell to fish
  sudo: true
  user: name={{ item.name }} shell=/usr/bin/fish
  when: item.shell == "fish"
  with_items: users
  tags: fish
