---
# tasks file for raid

- name: Install RAID package
  sudo: true
  yum: name=mdadm state=present
  tags: raid

- name: Check existing RAID devices
  sudo: true
  command: mdadm -D {{ item.device }}
  register: mdadm_status
  ignore_errors: true
  changed_when: false
  failed_when: false
  with_items: raid_devices
  tags: raid

- name: Initialize RAID devices
  sudo: true
  command: >
    mdadm -v --create {{ item.0.device }} --level={{ item.0.level }} --raid-devices={{ item.0.components | length }}
    {{ item.0.components | join(" ") }}
  when: item.1.rc != 0
  with_together:
    - raid_devices
    - mdadm_status.results
  tags: raid
