---
# tasks file for raid

- name: Install RAID package
  sudo: true
  dnf: name=mdadm state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: raid

- name: Install RAID package
  sudo: true
  yum: name=mdadm state=present
  when: ansible_pkg_mgr == "yum" or not (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: raid

- name: Check existing RAID devices
  sudo: true
  command: mdadm -D {{ item.device }}
  register: mdadm_status
  changed_when: false
  failed_when: false
  with_items: raid_devices
  tags: raid

- name: Assemble existing RAID devices
  sudo: true
  command: mdadm --assemble {{ item.0.device }} --force {{ item.0.components | join(" ") }}
  when: item.1.stderr == "mdadm':' cannot open {{ item.0.device }}':' No such file or directory"
  with_items:
    - raid_devices
    - mdadm_status.results
  tags: raid

- name: Initialize RAID devices
  sudo: true
  command: >
    mdadm -v --create {{ item.0.device }} --level={{ item.0.level }} --raid-devices={{ item.0.components | length }}
    {{ item.0.components | join(" ") }}
  when: item.1.rc != 0
  with_together:
    - raid_devices
    - mdadm_status.results
  tags: raid

- name: Scan RAID devices
  sudo: true
  command: mdadm --detail --scan
  register: mdadm_scan
  changed_when: false
  tags: raid

- name: Create /etc/mdadm.conf
  sudo: true
  template: dest=/etc/mdadm.conf src=mdadm.conf.j2
  tags: raid
