---
# tasks file for rpmfusion

- name: Add RPM Fusion repositories
  sudo: true
  dnf: name={{ item }} disable_gpg_check=true state=present
  with_items:
    - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_lsb.release }}.noarch.rpm"
    - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_lsb.release }}.noarch.rpm"
  tags: rpmfusion
