---
# tasks file for ui

- name: Install UI packages
  sudo: true
  dnf: name={{ item }} state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  with_items:
    - gnome-tweak-tool
    - dconf-editor
  tags: ui

- name: Show date in top bar for current user
  command: gsettings set org.gnome.desktop.interface clock-show-date true
  tags: ui

- name: Set automatic timezone change for current user
  command: gsettings set org.gnome.desktop.datetime automatic-timezone true
  tags: ui

- name: Change home folder keyboard shortuct for current user
  command: gsettings set org.gnome.settings-daemon.plugins.media-keys home '<Super>e'
  tags: ui

# - schema: org.gnome.desktop.wm.keybindings
#   key: switch-group
#   value: "['disabled']"
# - schema: org.gnome.desktop.wm.keybindings
#   key: switch-group-backward
#   value: "['disabled']"

- name: Apply global dark theme for current user
  ini_file:
    dest=/home/{{ ansible_user_id }}/.config/gtk-3.0/settings.ini
    option=gtk-application-prefer-dark-theme
    section=Settings
    value=1
  tags: ui

- name: Create terminal keyboard shortcut for current user
  command: gsettings set {{ item.schema }} {{ item.key }} {{ item.value }}
  with_items:
    - schema: org.gnome.settings-daemon.plugins.media-keys
      key: custom-keybindings
      value: "\"['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']\""
    - schema: "{{ ui_terminal_dconf_schema_start }}:{{ ui_terminal_dconf_schema_end }}"
      key: name
      value: 'Terminal'
    - schema: "{{ ui_terminal_dconf_schema_start }}:{{ ui_terminal_dconf_schema_end }}"
      key: command
      value: 'gnome-terminal'
    - schema: "{{ ui_terminal_dconf_schema_start }}:{{ ui_terminal_dconf_schema_end }}"
      key: binding
      value: '<Super>t'
  tags: ui

# - name: Create monitors config file for current user, root user & graphical login
#   sudo: true
#   copy:
#     src=monitors.xml.{{ ansible_hostname }}
#     dest={{ item.dir }}/.config/monitors.xml
#     owner={{ item.user }}
#     group={{ item.user }}
#     mode=0644
#   with_items:
#     - { user: "{{ ansible_user_id }}", dir: "/home/{{ ansible_user_id }}" }
#     - { user: "gdm", dir: "/var/lib/gdm" }
#   tags: ui

# - name: Create Vinagre configuration directory for current user
#   file:
#     path={{ vinagre_user_config_dir }}
#     state=directory
#     owner={{ ansible_user_id }}
#     group={{ ansible_user_id }}
#     mode=0755
#   tags: ui

# - name: Create Vinagre bookmarks for current user
#   template:
#     src=vinagre-bookmarks.xml.j2
#     dest={{ vinagre_user_config_dir }}/vinagre-bookmarks.xml
#     owner={{ ansible_user_id }}
#     group={{ ansible_user_id }}
#     mode=0644
#   tags: ui
