---
# tasks file for vagrant

- name: download Vagrant
  get_url: >
    url=https://dl.bintray.com/mitchellh/vagrant/{{ vagrant_rpm }}
    dest=/tmp/{{ vagrant_rpm }}

- name: install Vagrant
  sudo: true
  yum: >
    pkg=/tmp/{{ vagrant_rpm }}
    state=present
