---
# tasks file for google_chrome

- name: import Google GPG key
  sudo: true
  rpm_key: >
    key=https://dl-ssl.google.com/linux/linux_signing_key.pub
    state=present
  tags: google_chrome

- name: add Google Chrome repo
  sudo: true
  copy: >
    src=google-chrome.repo
    dest=/etc/yum.repos.d/google-chrome.repo
    owner=root
    group=root
    mode=0644
  tags: google_chrome

- name: install Google Chrome (stable)
  sudo: true
  yum: pkg=google-chrome-stable state=present
  tags: google_chrome
