---
# tasks file for ovirt-engine

- name: Install oVirt repository
  sudo: true
  yum: name={{ ovirt_repo }} state=present
  tags: ovirt-engine

- name: Install hosted oVirt engine setup
  sudo: true
  yum: name=ovirt-hosted-engine-setup state=present
  tags: ovirt-engine

- name: Create ovirt-engine entry in /etc/hosts
  sudo: true
  lineinfile:
    dest=/etc/hosts
    line="{{ ovirt_engine.address }} {{ ovirt_engine.hostname}}.{{ ansible_domain }}"
    regexp='.*{{ ovirt_engine.hostname }}\.{{ ansible_domain }}$'
    state=present
  tags: ovirt-engine

- name: Download CentOS ISO
  sudo: true
  get_url: dest=/tmp/{{ ovirt_centos_iso }} group=36 owner=36 url={{ ovirt_centos_mirror }}
  tags: ovirt-engine
