---
# tasks file for atom

- name: Install Atom
  sudo: true
  dnf: name={{ atom_url }} state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: atom

- name: Install Atom
  sudo: true
  yum: name={{ atom_url }} state=present
  when: ansible_pkg_mgr == "yum" and not (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: atom
