---
# tasks file for sublime_text

- name: download Sublime Text
  get_url: url={{ st3_url }} dest=/tmp/{{ st3_archive }}
  tags: sublime_text

- name: install Sublime Text
  sudo: true
  unarchive: src=/tmp/{{ st3_archive }} dest=/opt copy=no
  tags: sublime_text

- name: copy desktop item
  sudo: true
  command: >
    cp {{ st3_dir }}/sublime_text.desktop {{ applications_dir }}
    creates="{{ applications_dir }}/sublime_text.desktop"
  tags: sublime_text

- name: fix path in desktop item
  sudo: true
  replace: >
    dest={{ applications_dir }}/sublime_text.desktop
    regexp="/opt/sublime_text/"
    replace="{{ st3_dir }}"
  tags: sublime_text

- name: fix icon in desktop item
  sudo: true
  lineinfile: >
    dest={{ applications_dir }}/sublime_text.desktop
    regexp="(^Icon)=sublime-text"
    line="\1={{ st3_dir }}/Icon/128x128/sublime-text.png"
    backrefs=true
  tags: sublime_text

- name: install Package Control
  sudo: true
  get_url: >
    url={{ pkgcntrl_url }}
    dest="{{ st3_dir }}/Packages/Package Control.sublime-package"
    owner=root
    group=root
    mode=0664
  tags: sublime_text

- name: create SublimeGit settings file for current user
  template: >
    src=SublimeGit.sublime-settings.j2
    dest={{ st3_user_config_dir }}/SublimeGit.sublime-settings
    owner={{ username }}
    group={{ username }}
    mode=0644
  tags: sublime_text

- name: create Sublimerge license file for current user
  template: >
    src=Sublimerge.sublime-license.j2
    dest={{ st3_user_config_dir }}/Sublimerge.sublime-license
    owner={{ username }}
    group={{ username }}
    mode=0644
  tags: sublime_text

- name: create other settings files for current user
  copy: >
    src=/
    dest={{ st3_user_config_dir }}
    owner={{ username }}
    group={{ username }}
    mode=0644
  tags: sublime_text
