---
# tasks file for tlp

- name: Install TLP
  sudo: true
  dnf: name=tlp state=present
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: tlp

- name: Start TLP
  sudo: true
  service: name=tlp enabled=true state=started
  tags: tlp
