---
# tasks file for common

- name: Install common packages
  sudo: yes
  dnf: name={{ item }}  state=present
  with_items: common_packages
  when: ansible_pkg_mgr == "dnf" or (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: common

- name: Install common packages
  sudo: yes
  yum: name={{ item }}  state=present
  with_items: common_packages
  when: ansible_pkg_mgr == "yum" and not (ansible_distribution == "Fedora" and ansible_distribution_major_version >= 22)
  tags: common
