---
# file: laptop.yml

- hosts: 127.0.0.1
  roles:
    - { role: git, full_name: "Michael Goodness", email_address: "mgoodness@gmail.com" }
    - fstrim
    - tlp
    - xorg
    - google_chrome
    - google_talk_plugin
    - sublime_text
    - virtualbox
    - vagrant
    - docker
    - fish
    - common
    - vlc

