---
# file: laptop.yml

- hosts: 127.0.0.1
  roles:
    - { role: git, full_name: "Michael Goodness", email_address: "mgoodness@gmail.com" }
    - google_chrome
    - google_talk_plugin
    - sublime_text
    - docker
    - fish
    - common
    - vlc
    
