---
# tasks file for php

- name: Install PHP packages
  sudo: true
  yum: pkg={{ item }} state=present
  with_items:
    - php-pear-PHP-CodeSniffer
    - php-phpmd-PHP-PMD
    - npm
  tags: php

- name: Configure NPM global location
  shell: npm config set prefix {{ homedir }}/.npm
  tags: php

- name: Install NPM Less package
  npm: name=less state=present global=true
  tags: php

- name: Download PhpStorm
  get_url: url={{ phpstorm_url }} dest=/tmp{{ phpstorm_archive }}
  tags: php

- name: Install PhpStorm
  sudo: true
  unarchive: src=/tmp/{{ phpstorm_archive }} dest=/opt copy=no
  tags: php
